### ISSUE TITLE
Allow use of email address to login

### ISSUE THREAD

**Issue by shiftee** [Openwords/OpenwordsWebapp#1]
Web users today have dozens of accounts scattered across the web.
If you don't go to a site often it is not always easy to remember your username.

Therefore I suggest you allow users to login using a combination of email and password.
This can either replace the current use of a username or you could have an email/username field

**Comment by hanaldo** [comment]
Supported in version [0.2.6](https://github.com/Openwords/OpenwordsWebapp/commit/95852b6ed87f4c9c10ffe3a14c16e1d32764a5da)
