### ISSUE TITLE
Provide the ability to search for courses

### ISSUE THREAD

**Issue by Ads20000** [Openwords/OpenwordsWebapp#2]
[On the webapp](https://rose-openwords.b9ad.pro-us-east-1.openshiftapps.com/mobile/index.html) I can't search for a particular language course, please could that feature be implemented?

**Comment by hanaldo** [comment]
<img width="820" alt="2018-10-03 11 45 45" src="https://user-images.githubusercontent.com/4184020/46422292-03a7f100-c702-11e8-9714-f6adc95a39cb.png">
<img width="820" alt="2018-10-03 11 46 23" src="https://user-images.githubusercontent.com/4184020/46422299-060a4b00-c702-11e8-8d49-3a63d8ca1b74.png">
